### ISSUE TITLE
Change model only when 'Choose' has been selected

### ISSUE THREAD

**Issue by webchaz** [Jimdo/angular-spectrum-colorpicker#20]
Is there a way to have it change the model only when it's been 'chosen' by clicking the button, as oppose to every time a color is changed?

Thanks!

**Comment by seiyria** [comment]
Agreed, we'll have to downgrade to get this functionality because we send an HTTP request only when the color has been chosen, and we can't send one otherwise.

**Comment by Ehesp** [comment]
^^ This

No point in really calling it on change, if when you click the change button no event is triggered.

**Comment by Xiphe** [comment]
closing since stale. please reopen if still valid.
