### ISSUE TITLE
Upgrade bower.json dependency for spectrum to 1.6.0

### ISSUE THREAD

**Issue by quietlyconfident** [Jimdo/angular-spectrum-colorpicker#24]
1.5.2 is a few months old and 1.6.0 seems to work great.

**Comment by joscha** [comment]
sounds good :) Would you like to provide a PR for it?

**Comment by quietlyconfident** [comment]
Did so with #25

**Comment by Xiphe** [comment]
When you leave the 'issue' out of the commit message und just write `... fixes #24` you can auto-close issues.
Details in [closing-issues-via-commit-messages](https://help.github.com/articles/closing-issues-via-commit-messages/) :tada:
