### ISSUE TITLE
Allow spectrum-colorpicker to be an attribute

### ISSUE THREAD

**Issue by netzaffin** [Jimdo/angular-spectrum-colorpicker#26]
Hello,

thanks so far.

What about allowing spectrum-colorpicker not just an element but an attribute?
This way we could use native color inputs but have a polyfill for browsers like IE.

http://caniuse.com/#feat=input-color

Would be an easy fix, or is there something I don't see that stands in the way?

Kind regards,
Patrick

**Comment by joscha** [comment]
you mean `<input type="color">` renders as spectrum color picker?

**Comment by netzaffin** [comment]
Yes - if no native support is available.

Spectrum itself has a functionality like that i think: https://github.com/bgrins/spectrum/issues/1

**Comment by joscha** [comment]
If you'd provide a PR for that, I'd be happy to merge it!

**Comment by fernandopasik** [comment]
https://github.com/Jimdo/angular-spectrum-colorpicker/pull/37

**Comment by Xiphe** [comment]
closed with #37

**Comment by netzaffin** [comment]
thanks!
