### ISSUE TITLE
Setting "flat: true" results in $rootScope:inprog error

### ISSUE THREAD

**Issue by kvdv** [Jimdo/angular-spectrum-colorpicker#27]
First off: great module!

I noticed a minor issue though, when setting the option "flat" to true via the options attribute, I get this error:
`Error: [$rootScope:inprog] http://errors.angularjs.org/1.3.12/$rootScope/inprog?p0=%24digest`

Other options work just fine.
Angular version used: (stable) 1.3.12.

Thanks in advance for your response!

**Comment by joscha** [comment]
@kvdv could you provide a failing unit test?

**Comment by vbabiy** [comment]
I am also able to reproduce this

**Comment by hagayl** [comment]
I'm facing this issue as well
`Error: [$rootScope:inprog] $digest already in progress`

**Comment by joscha** [comment]
can anyone of you add a failing unit test please?

**Comment by cytsunny** [comment]
I got this issue too. Not sure how to write a unit test, but I think it is quite easy to reproduce the bug? All you need to do is just to add the flat:true to option.

**Comment by joscha** [comment]
@cytsunny the test is for regression as well, not only for showing that the problem exists - if it is easy to provoke the problem, it would be cool if you could just add a short test, please.

**Comment by klindberg** [comment]
I'm getting the same problem. I'd be happy to provide a test for you, if you'll let me know how to do it. 

Without 'flat: true' inside the options, the directive works very well. It would just be nice to have the palette being shown without having to click on something.

Thank you,
Ken

**Comment by Xiphe** [comment]
See [initialize-the-source-project](https://github.com/Jimdo/angular-spectrum-colorpicker#initialize-the-source-project)

and run `grunt test` in order to have the tests, run.

Then look into the [test folder](https://github.com/Jimdo/angular-spectrum-colorpicker/tree/master/test) and copy/adapt to you'r needs.

**Comment by Xiphe** [comment]
can anybody that had this error check if it still occurs with d3a1e5e5c060ba578275ce8d7773cac76dd51b45? 
Will soon be released as v1.4.2

**Comment by Xiphe** [comment]
i assume it works :)

**Comment by cytsunny** [comment]
It works but it seems the version under dist folder is not updated. The problem still exist if they download the js file directly. Would be great if the js file in the dist is updated as well.

**Comment by Xiphe** [comment]
I can not confirm that. As mentioned above, it has been released with `1.4.2`

see: https://github.com/Jimdo/angular-spectrum-colorpicker/commit/c17d25484ef4ab3180499186fe09b5f18bb52d84#diff-c5a4e30894019be35292c7a9993b08efR77
