### ISSUE TITLE
Update Spectrum to 1.6.2 to get rid of annoying Chrome warning

### ISSUE THREAD

**Issue by robbiet480** [Jimdo/angular-spectrum-colorpicker#28]
Upgrading Spectrum to 1.6.2 (which appears to be a non-breaking change) will squash the warning that many users are now seeing in Chrome (`The specified value '!' does not conform to the required format.  The format is '#rrggbb' where rr, gg, bb are two-digit hexadecimal numbers.`) 

See https://github.com/bgrins/spectrum/pull/296 and https://github.com/bgrins/spectrum/pull/292 for more info.

**Comment by joscha** [comment]
cool! Would you like to provide a PR with this change?

**Comment by robbiet480** [comment]
@joscha Done :)
