### ISSUE TITLE
Destroy spectrum on jQuery $destroy event instead of $scope.$destroy event

### ISSUE THREAD

**Issue by tomaszkrym** [Jimdo/angular-spectrum-colorpicker#30]
There is a time gap between broadcasting $scope.$destroy and removing the part of DOM. This causes that the input with hex value is displayed instead of colorpicker during $scope destruction

According to the angular documentation (https://code.angularjs.org/1.2.27/docs/api/ng/type/$rootScope.Scope)  there is also jQuery $destroy event emitted:

"Note that, in AngularJS, there is also a $destroy jQuery event, which can be used to clean up DOM bindings before an element is removed from the DOM."

Binding to this event causes that the spectrum is removed smoothly - I've tried it already:

```javascript
$element.on('$destroy', function(){
        	  $input.spectrum('destroy');
});
```

I can submit a PR, if this change is accepted.

**Comment by joscha** [comment]
@tomaszkrym sounds good - would you also be able to provide a failing test than will be fixed by the proposed change?
