### ISSUE TITLE
setting color dynamically 

### ISSUE THREAD

**Issue by anatlerner** [Jimdo/angular-spectrum-colorpicker#32]
I want that the default color will be set dynamically in rgba format in the color picker.
my options are :
                    ```   showAlpha: true,
    			showInput: true,
			flat: true,
			showButtons: false,
			 containerClassName: 'color-picker-container',
			 preferredFormat: 'rgb',
			 reflow: true```
how can i trigger to set the color option?

**Comment by Xiphe** [comment]
use `ng-model` on the `spectrum-colorpicker` directive (see [demo](https://github.com/Jimdo/angular-spectrum-colorpicker/blob/master/demo/index.html#L22-L27))

please reopen if this does not solve the problem ;)
