### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by okonet** [Jimdo/angular-spectrum-colorpicker#38]
Please publish the package to npm

**Comment by Xiphe** [comment]
in order to use this with webpack/browserify?

**Comment by okonet** [comment]
Yep!

**Comment by Xiphe** [comment]
Feels a little bit stange because we don't use npm features here :/
We'd need to set `dist/angular-spectrum-colorpicker.js` as the `main` file because the files in `src` don't use require. the `dist` file itself does not export anything, too.

**Comment by Xiphe** [comment]
But if that's fine for you, i'd be happy to publish :)

**Comment by Xiphe** [comment]
we're currently using it as a bower package in webpack with 
```
new webpack.ResolverPlugin(
  new webpack.ResolverPlugin.DirectoryDescriptionFilePlugin(
    "bower.json", ["main"]
  )
)
...
```

**Comment by Xiphe** [comment]
but we're migrating all the things to webpack + require so i probably improve this either way in the near future

**Comment by okonet** [comment]
I also use it this way right now. But it feels strange to not be able to install it via npm. Bower tries to be too smart, which isn't required when using webpack. 

Also, when installing using npm from this repository, it still trying install bower packages and build stuff in postinstall script. This should also probably be gone in oder to publish.

Regarding not exporting anything: I can imagine an `index.js` file in the root directory which will require the `dist` one and wrap it into a module which exports module name as a string: same as angular does.

**Comment by Xiphe** [comment]
sounds good to me. Since you seem to have a good opinion here and i'm currently low on time for this project. would you mind building a PR proposing this changes?

**Comment by okonet** [comment]
Let's see I find some time...

**Comment by Xiphe** [comment]
Ok, i'll see what i can do, too.

my long-term-goal would be to migrate the tooling of this repo to webpack and have both: a concatinated, classic bower module and some kind of entry that can be required by webpack and is in no way optimized. In order to get maximal optimisation from webpack (see http://webpack.github.io/docs/usage-with-bower.html#example-react)

**Comment by davidagee** [comment]
:+1: we recently moved away from bower for front-end package management and could definitely use an npm-ready version of this.

**Comment by Xiphe** [comment]
Sadly still the same situation for me, i don't have the time to refactor things here. i could just publish the bower version (`dist`-folder) to npm, let me know if that helps.

**Comment by duncangrist** [comment]
> let me know if that helps.

That would certainly help me!

Currently the postInstall action of the package.json always fails...

    npm ERR! Failed at the angular-spectrum-colorpicker@1.4.2 postinstall script 'bower install && ln -sf ./node_modules/grunt-cli/bin/grunt ./grunt && ./node_modules/protractor/bin/webdriver-manager update && ./grunt build'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the angular-spectrum-colorpicker package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     bower install && ln -sf ./node_modules/grunt-cli/bin/grunt ./grunt && ./node_modules/protractor/bin/webdriver-manager update && ./grunt build

**Comment by Xiphe** [comment]
Apparently @KennyWibowo already published the project on npm.
I just updated the packages and made some npm-specific changes. 
Can not publish the current version, though because i need to get publishing rights for the npm project.

**Comment by KennyWibowo** [comment]
Hi, sorry, I should've taken a temporary repository name up instead. Is there a way to transfer publishing rights to you?

**Comment by Xiphe** [comment]
ah, just wrote you an email, don't worry. you should be able to grant me rights here: https://www.npmjs.com/package/angular-spectrum-colorpicker/access

**Comment by Xiphe** [comment]
my npm e-mail is  npm@xiphe.net

**Comment by joscha** [comment]
You can also just use the CLI: https://docs.npmjs.com/cli/owner using @Xiphe npmjs name.

**Comment by Xiphe** [comment]
which would be @xiphe, too :)

**Comment by KennyWibowo** [comment]
Just added you in as a collaborator, should be working now :)

**Comment by Xiphe** [comment]
great, thanks. I'll close here - have a great day (*waves to @joscha)
