### ISSUE TITLE
Picker doesn't work in ng-repeat

### ISSUE THREAD

**Issue by Firzenizer** [Jimdo/angular-spectrum-colorpicker#41]
The color isn't changed in the model if picker is used in a repeater.

See this plunker:
http://plnkr.co/edit/AjJZWcuJ0Eaaw0O15qA4?p=preview

**Comment by Xiphe** [comment]
i see `Module 'angularSpectrumColorpicker' is not available! You either misspelled the module name or forgot to load it.` in the console, which indicates that this is a setup error.

**Comment by Firzenizer** [comment]
Hmm for some reason Chrome and IE refuse to load the script. It works on Firefox.

**Comment by Xiphe** [comment]
> In the video AngularJS MTV Meetup: Best Practices (2012/12/11), Miško explains "..if you use ng-model there has to be a dot somewhere. If you don't have a dot, you're doing it wrong.."

See: http://stackoverflow.com/a/17607794/1468875

I added a dot to your model and it works for me (in FF)
http://plnkr.co/edit/JJYB3o5DTwxIPrrDniH6?p=preview
