### ISSUE TITLE
tips for making edits to HTML elements used in colorpicker?

### ISSUE THREAD

**Issue by jpaulin** [Jimdo/angular-spectrum-colorpicker#42]
I wrote a few days earlier to the non-angularized component (also on Github) - the gridster.js

But I think this is better place, since it's exactly angular-spectrum-colorpicker that is in my use.

Once things have been laid (in source) in a component like the colorpicker, are there good practises to do changes that would mean modifying the HTML source, for example. I'd like to convert both the 'OK' and 'Cancel' be made with HTML Button input elements, not so that the Cancel is a text element.  

This mixed bag leads to problems in UI of the app, namely the buttons get slightly different vertical alignment - they don't sit on a common line. :-)

J

**Comment by Xiphe** [comment]
I think that is an implementation detail of the spectrum colorpicker. We opened bgrins/spectrum#350 for similar reasons. I do not see a clean way to fix this from inside this project.

**Comment by Xiphe** [comment]
i'll close this, please refer to the issue linked above
