### ISSUE TITLE
How to update color palette?

### ISSUE THREAD

**Issue by rockonslap** [Jimdo/angular-spectrum-colorpicker#44]
Hi I have some problem with color palette option. I need to update more color to the palette after spectrum has been initialized.

Thanks.

**Comment by Xiphe** [comment]
how are you trying to achieve this?
what was the expected result?
what happened instead?
could you provide a test that illustrates your problem?

**Comment by rockonslap** [comment]
I want user have ability to add more color to they palette  . For example. I have initial three default color such as #ff0000, #00ff00, #0000ff then user can type some hex color code and click button "Add" to add color  to palette. Now I can push color to scope object and spectrum add color to palette. But I need to pre-initial palette array.
Thanks.

**Comment by Xiphe** [comment]
Seems as if the [showSelectionPalette option](https://bgrins.github.io/spectrum/#options-showSelectionPalette) would suit your needs. 
You can pass spectrum options to the `options` attribute on the colorpicker directive

**Comment by jvanhees** [comment]
I have the same problem, but I am requesting a number of colors from a server and can't use local colors. Is there any way to send an event to the picker (or re-init) that it should reload the palette?

**Comment by jvanhees** [comment]
Pull request #45 would solve the issue with the $watch function not triggering, thus updating the palette when the variable changes as you would expect from Angular.

**Comment by Xiphe** [comment]
#45 is merged and released with [`v1.4.3`](https://github.com/Jimdo/angular-spectrum-colorpicker/tree/v1.4.3) 

please reopen if this does not solve your problem.
