### ISSUE TITLE
cannot npm install - postinstall failing

### ISSUE THREAD

**Issue by martinsson** [Jimdo/angular-spectrum-colorpicker#47]
1st problem when installing 
```
Loading "Gruntfile.js" tasks...ERROR
>> Error: Cannot find module './tasks/helpers'
Warning: Task "build" not found. Use --force to continue.

Aborted due to warnings.

```

Because this is only needed for developing on the library I tried to install it with --ignore-script

But whenever I do "npm install" in my project it tries to install angular-spectrum-colorpicker again this time without --ignore-script. So that fails because I don't have protractor at the right place. 

```
> angular-spectrum-colorpicker@1.4.4 postinstall /Users/johan/client/bee/nextgen/front-fresh/node_modules/angular-spectrum-colorpicker
> bower install && ln -sf ./node_modules/grunt-cli/bin/grunt ./grunt && ./node_modules/protractor/bin/webdriver-manager update && ./grunt build
...
...

angular-mocks#1.5.1 bower_components/angular-mocks
└── angular#1.5.1
sh: ./node_modules/protractor/bin/webdriver-manager: No such file or directory

npm ERR! Darwin 15.3.0
npm ERR! argv "node" "/Users/johan/.node/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.14.12
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

```
Would it not be possible to remove those dev dependencies whenever I include it as a library?

**Comment by Xiphe** [comment]
yeah, i understand the problem and had it already with another project.

what would be the common way to go here?

what i did in the other project is moving the `postinstall` hook to a `setup` npm task and then use `npm install && npm run setup` for development.

**Comment by martinsson** [comment]
Thanks for your quick response.

Yes that's a solution that won't interfere with the npm install of anyone using this lib.

I guess you could also consider some of the non install phases, like pretest for some of the things you need to do for dev. For a list of phases : https://docs.npmjs.com/misc/scripts. That being said I'd use the solution you're suggesting to avoid rerunning it for every test run.

**Comment by Xiphe** [comment]
here we go, if anybody has a better idea please share it :)

Braindump: Technically it should be possible to check if the `npm install` comes from the project folder or from another project that uses this as a dependency. Then the script could execute the setup steps dynamically. But this seems to be a bit to much magic...

**Comment by Xiphe** [comment]
should be fine with [`v1.4.5`](https://github.com/Jimdo/angular-spectrum-colorpicker/releases/tag/v1.4.5)

**Comment by martinsson** [comment]
Great thanks, integrated and seems to work. Cheers

**Comment by joscha** [comment]
@xiphe I think in the long-term using `prepublish` might be easier.

**Comment by Xiphe** [comment]
@joscha I think prepublish serves a different use case. what we're doing with `setup` is preparing the dev environment (by installing bower and webdriver). prepublish would literally run pre-`npm publish`, which would only make sense once a working dev-env is already in place, like you would not `npm publish` without having webdriver installed.

**Comment by joscha** [comment]
You are right, my bad!
