### ISSUE TITLE
$input.spectrum is not a function

### ISSUE THREAD

**Issue by karthikajjan** [Jimdo/angular-spectrum-colorpicker#48]
Using angular spectrum in ionic framework, error happen in my code,

**Html code:**
`<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, width=device-width">
    <title></title>

    <link href="lib/ionic/css/ionic.css" rel="stylesheet">
    <link href="css/style.css" rel="stylesheet">
    <link href="lib/angular-bootstrap-colorpicker/css/colorpicker.css" rel="stylesheet">
	
	
	<link href="lib/spectrum/spectrum.css" rel="stylesheet">

    

    
    <script src="lib/ionic/js/ionic.bundle.js"></script>
	<script src="lib/ionic-platform-web-client/dist/ionic.io.bundle.min.js"></script>

    
    <script src="lib/ngCordova/dist/ng-cordova.js"></script>
    <script src="cordova.js"></script>
    
    <link rel="stylesheet" href="lib/fullcalendar/dist/fullcalendar.css"/>
    
    <script type="text/javascript" src="lib/jquery/dist/jquery.min.js"></script>
    <script type="text/javascript" src="lib/moment/min/moment.min.js"></script>
    <script type="text/javascript" src="lib/angular/angular.min.js"></script>
    <script type="text/javascript" src="lib/angular-ui-calendar/src/calendar.js"></script>
    <script type="text/javascript" src="lib/fullcalendar/dist/fullcalendar.min.js"></script>
    <script type="text/javascript" src="lib/fullcalendar/dist/gcal.js"></script>
	
	
	<script src="lib/angular-google-chart/ng-google-chart.js"></script>
	
	
	<script src="lib/angular-bootstrap-colorpicker/js/bootstrap-colorpicker-module.js"></script>
	
	
	<script src="lib/spectrum/spectrum.js"></script>
	<script src="lib/angular-spectrum-colorpicker/dist/angular-spectrum-colorpicker.js"></script>
	
	
    <script src="js/app.js"></script>
    <script src="js/controllers.js"></script>
    <script src="js/calendar.js"></script>
    <script src="js/services.js"></script>
	
  </head>

  <body ng-app="starter">
    <ion-nav-view></ion-nav-view>
    <ion-content><spectrum-colorpicker ng-model="yourFancyModel"></spectrum-colorpicker></ion-content>
  </body>
</html>`

**App.js:**
`angular.module('starter', ['ionic', 'starter.controllers', 'starter.services', 'colorpicker.module', 'angularSpectrumColorpicker'])`

**Error received on firebugs:**
Error: `$input.spectrum is not a function`
.link@http://172.21.4.139:8100/lib/angular-spectrum-colorpicker/dist/angular-spectrum-colorpicker.js:141:5
cloneAndAnnotateFn/<@http://172.21.4.139:8100/lib/ionic/js/ionic.bundle.js:21956:41
invokeLinkFn@http://172.21.4.139:8100/lib/ionic/js/ionic.bundle.js:21962:9
nodeLinkFn@http://172.21.4.139:8100/lib/ionic/js/ionic.bundle.js:21462:1
compileTemplateUrl/<@http://172.21.4.139:8100/lib/ionic/js/ionic.bundle.js:21692:1
processQueue@http://172.21.4.139:8100/lib/ionic/js/ionic.bundle.js:27879:28
scheduleProcessQueue/<@http://172.21.4.139:8100/lib/ionic/js/ionic.bundle.js:27895:27
$RootScopeProvider/this.$get</Scope.prototype.$eval@http://172.21.4.139:8100/lib/ionic/js/ionic.bundle.js:29158:16
$RootScopeProvider/this.$get</Scope.prototype.$digest@http://172.21.4.139:8100/lib/ionic/js/ionic.bundle.js:28969:15
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://172.21.4.139:8100/lib/ionic/js/ionic.bundle.js:29263:13
done@http://172.21.4.139:8100/lib/ionic/js/ionic.bundle.js:23676:36
completeRequest@http://172.21.4.139:8100/lib/ionic/js/ionic.bundle.js:23848:7
requestLoaded@http://172.21.4.139:8100/lib/ionic/js/ionic.bundle.js:23789:1

<span ng-model="yourFancyModel">

**Comment by Xiphe** [comment]
try loading jQuery before angular/ionic.

angular will probably not pickup jQuery if it's being loaded afterwords and then use the built-in jQuery-lite, resulting in a situation where `$input` is a jqLite element and not a real jQuery element. While only the latter does actually has the plugin registry spectrum is registering on.

**Comment by karthikajjan** [comment]
I include jquery before ionic now it's working fine.
Thanks Xiphe.

**Comment by Xiphe** [comment]
perfect, glad i could help
